import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />

        {children}
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="flex justify-between items-center p-4 border-b">
      <h1 className="text-2xl font-bold">Next.js learn</h1>
      <nav className="space-x-4">
        <Link href="/">Home</Link>
        <Link href="/segment1">Segment1</Link>
      </nav>
    </header>
  );
}
